name: Release

on:
  workflow_dispatch

concurrency:
  group: "release"
  cancel-in-progress: true

permissions:
  packages: write # Required for calling the docker workflow
  contents: write # Required for creating releases

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Version
        id: version
        run: echo "name=v${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build x86-64
        env:
          version: ${{ steps.version.name }}
        run: dart compile exe bin/main.dart -o "tudo-server.x86-64.$version"

      - name: Build arm-64
        env:
          version: ${{ steps.version.name }}
        run: dart compile exe --target-os=linux --target-arch=arm64 bin/main.dart -o "tudo-server.arm-64.$version"

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          version: ${{ steps.version.name }}
        with:
          tag_name: "$version"
          name: "$version"
          generate_release_notes: true
          files: |
            "tudo-server.x86-64.$version"
            "tudo-server.arm-64.$version"

  deploy:
    name: Deploy tudo.cachapa.net
    uses: ./.github/workflows/deploy.yml
    needs: build
    secrets: inherit
    with:
      version: "${{ needs.build.outputs.version }}"


  docker:
    name: Docker
    uses: ./.github/workflows/docker.yml
    needs: build
    with:
      version: "${{ needs.build.outputs.version }}"
